- GeoChemistryPy/plot/geochemistry_plot/elements_ratio_map.py
a function of plotting the ratio of two different chemical elements
>  elements_ratio_map

- .idea/geochemistrypy.iml
- .idea/inspectionProfiles/profiles_settings.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- .idea/workspace.xml
- geochemistrypy/model/classification.py
Add plot_svc_function to classification.py
>  Perfect function

- geochemistrypy/model/classification.py
Xgboostclassification add attribute 'importance_type', delete function'plot()'
> Xgboostclassification add attribute importance_type,delete function 'plot()'

- geochemistrypy/model/clustering.py
1. A small update, this can make result in color block .
2. It is more suitable for KMeans drawings.
> Add result in color plot  2d graph in clustering.py

- geochemistrypy/global_variable.py
- geochemistrypy/model/regression.py
- geochemistrypy/process/regress.py
1. append the function 'Plot SVR Regression' for SVM Regression.
> Add SVM regression Model

- geochemistrypy/data/data_readiness.py
- geochemistrypy/global_variable.py
- geochemistrypy/model/_base.py
- geochemistrypy/model/classification.py
- geochemistrypy/model/func/algo_regression/_dnn.py
- geochemistrypy/model/regression.py
- geochemistrypy/process/regress.py
1)Add class DNNregression in regression.py
2)Add function 'float_input' and 'tuple_input' in data_readiness.py
> Add class DNNRegression and two input functions

- geochemistrypy/model/classification.py
Update the Decision Boundary function for Decision Tree and Random Forest
> Clustering Module Framework Update

- geochemistrypy/global_variable.py
- geochemistrypy/model/func/algo_regression/_linear.py
- geochemistrypy/model/regression.py
- geochemistrypy/process/regress.py
1. Added functions 'show formula' and 'plot 2d/3d graph' in class Linearregression.
2. Reconstructed class Linearregression.
> Add class Linearregression in regression.py

- geochemistrypy/model/classification.py
- geochemistrypy/model/func/algo_classification/_Xgboost.py
- geochemistrypy/model/func/algo_classification/_decision_tree.py
- geochemistrypy/model/func/algo_classification/_logistic.py
- geochemistrypy/model/func/algo_clustering/_cluster.py
- geochemistrypy/model/func/algo_clustering/_dbscan.py
Integrate and reconstruct the framework of Xgboost、DecisionTree and logistic in classification model
> Reconstruct the framework of  classification model

- geochemistrypy/model/clustering.py
- geochemistrypy/model/func/algo_clustering/_cluster.py
- geochemistrypy/process/cluster.py
1.Refactor plot_silhouette_diagram function in _cluster.py 2.Refactor scatter2d function in _cluster.py
3.Refactor scatter3d function in _cluster.py
> Refactor the Kmeans code into cluster.py

- geochemistrypy/model/func/algo_regression/_rf.py
- geochemistrypy/model/func/algo_regression/_xgboost.py
- geochemistrypy/model/regression.py
- requirements.txt
1. Optimize Xgboost regression (feature importances)
2. Reconstructing Random Forest regression
> Reconstructing Xgboost regression and  RF regression( new branch)

- geochemistrypy/model/clustering.py
1.Rename the variable “component_num” to “data_dimension”. This is more consistent with the meaning of the variable. 2.Add the comment of data_dimension.
3.Optimize dimensional graph judgment.
4.Change the title of the plot.
> Fix and optimize  plotting functions in clustering.py

- geochemistrypi/data_mining/data/data_readiness.py
Error includs: SyntaxError, NameError, UnicodeDecodeError, IndexError, TypeError.
> Add error management for user input

- geochemistrypi/data_mining/model/_base.py
- geochemistrypi/data_mining/model/classification.py
- geochemistrypi/data_mining/model/clustering.py
- geochemistrypi/data_mining/model/func/algo_classification/_svm.py
- geochemistrypi/data_mining/model/func/algo_clustering/_dbscan.py
1）Added configuration related to drawing in model.py ->_base.py
2) Modify the drawing mode of DBSCAN
3）Modify the drawing mode of SVM
> Uniform drawing format

- geochemistrypi/data_mining/model/func/algo_regression/_xgboost.py
- geochemistrypi/data_mining/model/regression.py
invoke image_config on xgboost regression
> Optimize the Xgboost regression for plotting

- geochemistrypi/data_mining/model/classification.py
- geochemistrypi/data_mining/model/func/algo_classification/_common.py
Add plot_precision_recall and plot_ROC functions in classification.py.
> Add two  common functions in classification.py

- geochemistrypi/data_mining/UI.py
Added a UI interface to the data entry section to further facilitate user use.
The user can select the data file to be processed either :
1) by typing in a text box.
2) by clicking the mouse.
> Added a UI interface to the data entry section

- geochemistrypi/data_mining/data/data_readiness.py
- geochemistrypi/data_mining/pipeline.py
- geochemistrypi/data_mining/plot/map_plot.py
Optimize the drawing function of the map, take the latitude and longitude data as the parameter, if the user data set does not have the latitude and longitude name, it will skip the map function by default, if there is, it can provide the user to choose whether to draw or not.
> Optimized data entry detection and world map functions

- geochemistrypi/data_mining/data/data_readiness.py
Optimize the following：
1）Identify specific problems with specific columns of data
2）A vacancy judgment is triggered only if the column is all vacancy values
> Optimize the ability to detect the data type of the selected subdata.

- geochemistrypi/data_mining/utils/base.py
Check that the original file exists, and if it does, add a number after the filename to distinguish.
> improvement：Keeping files from being overwritten

- geochemistrypi/data_mining/data/feature_engineering.py
- geochemistrypi/data_mining/pipeline.py
- geochemistrypi/data_mining/plot/map_plot.py
**Word Map:**
Fixed a bug that appeared when data had strings.
**Feature Engineering**
- Use the eval function to replace the original stack function.Now, it can achieve the following operations:
1.   Basic four operations
2.   Simple trigonometric operations
3.   Logarithmic operations with base e
4.   Calculate the average value
- Implement basic monitoring functions. Currently it can give  simple  alerts when there is a problem with the input.
> Fix in word map & Improvement in feature engineering

- geochemistrypi/data_mining/plot/map_plot.py
1.Modified world mapping, substitute cartopy.py for basemap.py
> perf: Modified world mapping, substitute cartopy for basemap

- geochemistrypi/data_mining/cli_pipeline.py
- geochemistrypi/data_mining/data/statistic.py
The Wilcoxon signed rank test is replaced by kruskal test.
> fix:Fixed the problem with the statistics module failing

- docs/source/Model Example/Regression/Regression.md
- docs/source/User Guide.md
- geochemistrypi/data_mining/constants.py
- geochemistrypi/data_mining/data/data_readiness.py
- geochemistrypi/data_mining/model/classification.py
- geochemistrypi/data_mining/model/func/algo_classification/_multi_layer_perceptron.py
- geochemistrypi/data_mining/model/func/algo_regression/_multi_layer_perceptron.py
- geochemistrypi/data_mining/model/regression.py
- geochemistrypi/data_mining/process/classify.py
- geochemistrypi/data_mining/process/regress.py
change the name of the DNN ( Deep Neural Network )to the MLP(Multi-layer Perceptron)
> style：change the name of the DNN to MLP

- docs/source/Model Example/Regression/Regression.md
- docs/source/User Guide.md
- geochemistrypi/data_mining/constants.py
- geochemistrypi/data_mining/data/data_readiness.py
- geochemistrypi/data_mining/model/classification.py
- geochemistrypi/data_mining/model/func/algo_classification/_multi_layer_perceptron.py
- geochemistrypi/data_mining/model/func/algo_regression/_multi_layer_perceptron.py
- geochemistrypi/data_mining/model/regression.py
- geochemistrypi/data_mining/process/classify.py
- geochemistrypi/data_mining/process/regress.py
change the name of the DNN ( Deep Neural Network )to the MLP(Multi-layer Perceptron)
> style: change the name of the DNN to MLP

- geochemistrypi/data_mining/data/data_readiness.py
- geochemistrypi/data_mining/data/feature_engineering.py
- geochemistrypi/data_mining/data/statistic.py
1) Solve the problem of list data selection out of range.
2) Solve the problem of input format in the feature engineering section.
> fix: solve the problem of list data selection out of range and input format in the feature engineering section.

- geochemistrypi/data_mining/data/data_readiness.py
1) A prompt will be given when the user proceeds to the next step without entering anything.
2) An attempt to read a csv file.
3) Solve possible irregularities in user input numbers, such as: [88,16].
> fix: solve the error problem when the data selection input is null &  an attempt to read a csv file & a possible problem of input numbers

- geochemistrypi/cli.py
- geochemistrypi/data_mining/cli_pipeline.py
- geochemistrypi/data_mining/data/data_readiness.py
- geochemistrypi/data_mining/data/feature_engineering.py
- geochemistrypi/data_mining/data/imputation.py
- geochemistrypi/data_mining/data/inference.py
- geochemistrypi/data_mining/data/preprocessing.py
- geochemistrypi/data_mining/model/_base.py
- geochemistrypi/data_mining/model/classification.py
- geochemistrypi/data_mining/model/func/algo_classification/_common.py
- geochemistrypi/data_mining/model/regression.py
- geochemistrypi/data_mining/plot/statistic_plot.py
- geochemistrypi/data_mining/process/_base.py
- geochemistrypi/data_mining/process/classify.py
- geochemistrypi/data_mining/process/cluster.py
- geochemistrypi/data_mining/process/decompose.py
- geochemistrypi/data_mining/process/regress.py
- geochemistrypi/data_mining/utils/base.py
- geochemistrypi/start_cli_pipeline.py
(1) build up model inference module by constructing the transform pipeline. 
(2) refactor feature engineering module to allow reproduce the same operation on inference data. 
(3) refactor all transformers' output to log the configuration. 
(4) add cli command to use model inference.
> feat: append model inference functionality to the pipeline.

- geochemistrypi/data_mining/constants.py
- geochemistrypi/data_mining/model/classification.py
- geochemistrypi/data_mining/model/func/algo_classification/_gradient_boosting.py
- geochemistrypi/data_mining/model/regression.py
- geochemistrypi/data_mining/process/classify.py
add gradient boosting classification which can automatically tune hyperparameters .
> feat: add gradient boosting classification

- geochemistrypi/data_mining/cli_pipeline.py
- geochemistrypi/data_mining/constants.py
- geochemistrypi/data_mining/data/inference.py
- geochemistrypi/data_mining/data/preprocessing.py
feat: add feature selection function.
> feat: add feature selection function.

- geochemistrypi/data_mining/data/data_readiness.py
- geochemistrypi/data_mining/plot/map_plot.py
1. Be able to recognize Chinese parentheses，such as 【 】
2. Eliminates the effect of Spaces in the input
3. Added longitude and latitude identification symbols for the world map
> perf: Added the recognition of Chinese parentheses and Spaces

- docs/source/For User/Model Example/Classification/classification.md
- docs/source/Home/Introduction.md
1）Add the mind map for Geochemistry π 
2）Update  Yu Cheng's well-developed classification.md
> docs:Add the mind map for Geochemistry π and update Yu Cheng's well-developed classification.md

- README.md
- docs/source/Home/Introduction.md
Update Geochemistry π Mind Map in README.md & Introduction.md
> docs:Update Geochemistry π Mind Map in README.md & Introduction.md

- geochemistrypi/data_mining/constants.py
- geochemistrypi/data_mining/model/detection.py
- geochemistrypi/data_mining/model/func/algo_abnormaldetection/_iforest.py
- geochemistrypi/data_mining/process/detect.py
feat: Add local outlier factor algorithm to abnormal detection work flow base
> feat: Add local outlier factor algorithm to abnormal detection work flow base

- geochemistrypi/data_mining/model/decomposition.py
Correct the parameters passed to the plotting function in PCA Decomposition
> fix: Correct the parameters passed to the plotting function in PCA Decomposition
